### ISSUE TITLE
fasstr: Date_Validate Error

### ISSUE THREAD

**Issue by Rpaq** [bcgov/fasstr#93]
Hello, I am wanting to pull information from 2 gauge stations using fasstr but I get these messages:

**Station number: 07GB003**

Error in date_validate():
! Corrupt Date with unknown type logical.
ℹ In file 'type-date-time.c' at line 344.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
Please report it at https://github.com/r-lib/vctrs/issues with a reprex ([https://https://tidyverse.org/help/](https://https//tidyverse.org/help/)) and the full backtrace.
Backtrace:
▆

├─fasstr::calc_annual_lowflows(station_number = "07GB003", roll_days = 7)
│ ├─base::$<-(*tmp*, "MIN_DATE", value = <date>)
│ ├─dplyr:::$<-.grouped_df(*tmp*, "MIN_DATE", value = <date>)
│ ├─base::NextMethod()
│ └─tibble:::$<-.tbl_df(*tmp*, "MIN_DATE", value = <date>)
│ └─tibble:::tbl_subassign(...)
│ └─tibble:::vectbl_recycle_rhs_rows(...)
│ ├─base::withCallingHandlers(...)
│ └─vctrs::vec_recycle(value[[j]], nrow)
│ └─vctrs (local) <fn>()
│ └─vctrs::vec_proxy(x = x)
│ └─vctrs:::date_validate(x)
└─rlang:::stop_internal_c_lib(...)
└─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Station number: 07GB001**

Error in date_validate():
! Corrupt Date with unknown type logical.
ℹ In file 'type-date-time.c' at line 344.
ℹ Install the winch package to get additional debugging info the next time you get this error.
ℹ This is an internal error that was detected in the vctrs package.
Please report it at https://github.com/r-lib/vctrs/issues with a reprex ([https://https://tidyverse.org/help/](https://https//tidyverse.org/help/)) and the full backtrace.
Backtrace:
▆

├─fasstr::calc_annual_lowflows(station_number = "07GB001", roll_days = 7)
│ ├─base::$<-(*tmp*, "MIN_DATE", value = <date>)
│ ├─dplyr:::$<-.grouped_df(*tmp*, "MIN_DATE", value = <date>)
│ ├─base::NextMethod()
│ └─tibble:::$<-.tbl_df(*tmp*, "MIN_DATE", value = <date>)
│ └─tibble:::tbl_subassign(...)
│ └─tibble:::vectbl_recycle_rhs_rows(...)
│ ├─base::withCallingHandlers(...)
│ └─vctrs::vec_recycle(value[[j]], nrow)
│ └─vctrs (local) <fn>()
│ └─vctrs::vec_proxy(x = x)
│ └─vctrs:::date_validate(x)
└─rlang:::stop_internal_c_lib(...)
└─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)

**Comment by DavisVaughan** [comment]
Hi, vctrs author here. I do think this is a fasstr issue. 

You patch up `ifelse()` `<Date>` issues here
https://github.com/bcgov/fasstr/blob/7c6fac22f598217dea8da548278278e72fcd392c/R/calc_annual_lowflows.R#L167

But in the case of all `NA` values this returns a _logical_ column of `NA`s that you then add a `"Date"` class too, and this is incorrect. It is what happens in the user's report above, which is reproducible from

```r
# tidyhydat::download_hydat()
fasstr::calc_annual_lowflows(station_number = "07GB003", roll_days = 7)
``` 

The `<Date>` class in R needs to be backed by a double column (sometimes integer, but that is less common these days and frowned upon)

You should be able to just use `dplyr::if_else()` instead and then you shouldn't have to worry about reclassing at all

**Comment by ashjolly** [comment]
Hi @jongoetz! Also checking in on this error. This can also be replicated within other functions in fasstr beyond the calc_annual_lowflows.R function; for example:

`compute_annual_frequencies(station_number = "07GB003")`

I don't see where the same 'patch' for date class issues is applied within either 'compute_annual_frequencies.R' or 'calc_annual_stats.R' files, so this error extends beyond just the 'class(lowflow_stats_temp$MIN_DATE) <- "Date"'.

**Comment by jongoetz** [comment]
Hi all! I looked through the code and replaced the line in question (and in other functions) with the following and should now work without the error:
` lowflow_stats_temp$MIN_DATE <- as.Date(lowflow_stats_temp$MIN_DATE, origin = "1970-01-01")`
See commit 8368e437a301049e5b70fa8f69dbcd6ea302fd5f.

Feel free to use/test the github main version with the correction while I get it prepped to push up to CRAN again soon.

I will note, however, the error popped by because of the source data, station_number = '07GB003', where it is a seasonal station with many missing dates for all years, and by default did not calculate any annual minimums (R didnt like assigning Date class to just NA's). So even with the code fix, the results are still a table filled with all NA's. To obtain values, can use the ignore_missing or allowed_missing arguments and/or filter for just specific months using the months argument.

@ashjolly compute_annual_frequencies(station_number = "07GB003") will still produce an error unless missing dates are managed/months filtered as well. I could potentially try to add in a stop error if this is the case to make it more apparent.

**Comment by Rpaq** [comment]
Thank you all for your help! 

@jongoetz, there seems to be another error when trying the same logic for **Station Number 07GB001**, are you able to fix this one as well? I am getting the following error:
![image](https://user-images.githubusercontent.com/126519828/226646888-67615f19-4ac8-43ac-9795-a8173b714c0d.png)

**Comment by jongoetz** [comment]
Hi @Rpaq. The error you are seeing is from fasstr itself. Right now the function cannot fit zero or negative values with the PIII distribution in the function. If you still want to compute the frequency without zero/negative values (understanding what the means for your analysis), you may need to look through the data  (using calc_annual_lowflows) to see which years have those zero or negative flow values and exclude those years (eg. exclude_years = 2003 for your example). Hopefully that helps.

**Comment by Rpaq** [comment]
Hi @jongoetz,

Thank you for the information! However, similar to the error for the 07GB003 gauge station, the **07GB001** gauge station is still showing a similar error so I am unable to do any type of analysis for this station, even the calc_annual lowflows function. 

Here is the screenshot of the error: 
![image](https://user-images.githubusercontent.com/126519828/226686381-9cd8f761-2188-4f9f-b2ef-091dccb579fa.png)

**Comment by jongoetz** [comment]
@Rpaq did you install the fasstr devel version from GitHub with the bug fix as suggested? If the problem still persists, let me know as the function works fine on my system now with the fix I made. Can install the dev version with the following code.
`remotes::install_github("bcgov/fasstr")`

However, the main issue here is that this station (like 07GB003) is a seasonal station so there are no results if missing dates are not managed. Adding in some checks in your scripts may help catch this before getting the error may be helpful; for example checking for number of missing days per year using the screen_flow_data() function.

**Comment by jongoetz** [comment]
Is now on CRAN and hopefully fully resolved!
